spring:
  datasource:
    url: jdbc:h2:mem:~/.h2/db;
    driverClassName: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true